### ISSUE TITLE
Health Check Using URL giving an error

### ISSUE THREAD

**Issue by japneet-sahni** [orachide/ansible-role-springboot#1]
Hi,

I am getting below error on executing below piece of ansible code for health check using URL. Any idea what is the issue with.

![image](https://user-images.githubusercontent.com/10338163/42813193-726cd396-89c0-11e8-91a4-e720c60760fa.png)

![image](https://user-images.githubusercontent.com/10338163/42813154-4fe57c6a-89c0-11e8-8a73-e51c3e2b84e6.png)

**Comment by orachide** [comment]
Hello,

Thanks for your interest to this project.

I'am not sure about what wrong in your case (the error msg said `result has no attribute status` that mean the uri module fail to request your url), but could you please re-execute your playbook with `-vvv` to have more verbose details.

Maybe it's a self signed certificate issue with this URL `httpS://localhost:8443/health`

If it is a certificate issue, you can add `validate_certs: no` to the uri module parameters, i'll patch this very soon to allow to configure this for the role.

Let me know !!

**Comment by japneet-sahni** [comment]
Hello,

This is the verbose details for the above error. I had added validate_certs: no as well in uri module parameters.

Verbose Details given below

`TASK [service_substitution : Healthcheck | Wait for substitution application to be healthy on URLs https://localhost:8443/health] ***

<198.18.XX.XXX> ESTABLISH SSH CONNECTION FOR USER: XXXXXXX
<198.18.XX.XXX> (0, '\r\n{**"status": 200**, "cookies": {}, "date": "Tue, 17 Jul 2018 12:40:57 GMT", "x_application_context": "one-substitutions:8443", "url": "https://localhost:8443/health", "transfer_encoding": "chunked", "changed": false, "vary": "Accept-Encoding", "connection": "close", "invocation": {"module_args": {"directory_mode": null, "force": false, "remote_src": null, "status_code": ["200"], "body_format": "raw", "owner": null, "follow": false, "client_key": null, "group": null, "use_proxy": true, "unsafe_writes": null, "setype": null, "content": null, "serole": null, "follow_redirects": "safe", "return_content": false, "method": "GET", "body": null, "timeout": 30, "src": null, "dest": null, "selevel": null, "force_basic_auth": false, "removes": null, "http_agent": "ansible-httpget", "regexp": null, "url_password": null, "url": "https://localhost:8443/health", "validate_certs": false, "seuser": null, "client_cert": null, "creates": null, "headers": {}, "delimiter": null, "mode": null, "url_username": null, "attributes": null, "backup": null}}, "json": {"status":"UP","serviceProductSubstitutionsHealthCheck":{"status":"UP"},"diskSpace":{"status":"UP"},"couchbase":{"status":"UP"},"hystrix":{"status":"UP"}}, "content_type": "application/json;charset=UTF-8", "msg": "OK (unknown bytes)", "redirected": false}\r\n', 'Shared connection to 198.18.XX.XXX closed.\r\n')
fatal: [sbs-sint-spr1]: FAILED! => {"msg": "The conditional check 'result.status == 200' failed. The error was: error while evaluating conditional (result.status == 200): 'dict object' has no attribute 'status'"}`

**Comment by orachide** [comment]
Here is your formated result:
```json
{
    "status": 200, // As you can see the status exist in the result and status == 200 as expected
    "cookies": {

    },
    "date": "Tue, 17 Jul 2018 12:40:57 GMT",
    "x_application_context": "one-substitutions:8443",
    "url": "https://localhost:8443/health",
    "transfer_encoding": "chunked",
    "changed": false,
    "vary": "Accept-Encoding",
    "connection": "close",
    "invocation": {
        "module_args": {
            "directory_mode": null,
            "force": false,
            "remote_src": null,
            "status_code": [
                "200"
            ],
            "body_format": "raw",
            "owner": null,
            "follow": false,
            "client_key": null,
            "group": null,
            "use_proxy": true,
            "unsafe_writes": null,
            "setype": null,
            "content": null,
            "serole": null,
            "follow_redirects": "safe",
            "return_content": false,
            "method": "GET",
            "body": null,
            "timeout": 30,
            "src": null,
            "dest": null,
            "selevel": null,
            "force_basic_auth": false,
            "removes": null,
            "http_agent": "ansible-httpget",
            "regexp": null,
            "url_password": null,
            "url": "https://localhost:8443/health",
            "validate_certs": false,
            "seuser": null,
            "client_cert": null,
            "creates": null,
            "headers": {

            },
            "delimiter": null,
            "mode": null,
            "url_username": null,
            "attributes": null,
            "backup": null
        }
    },
    "json": {
        "status": "UP",
        "serviceProductSubstitutionsHealthCheck": {
            "status": "UP"
        },
        "diskSpace": {
            "status": "UP"
        },
        "couchbase": {
            "status": "UP"
        },
        "hystrix": {
            "status": "UP"
        }
    },
    "content_type": "application/json;charset=UTF-8",
    "msg": "OK (unknown bytes)",
    "redirected": false
}
```

What is your ansible version `ansible --version` ?

Anyway my advice is to use the role from galaxy `ansible-galaxy install orachide.springboot-service` to use it or just Fork this repository.

Regarding your result, the https call works well, it seem you have an issue with the 
`register: result` part

**Comment by japneet-sahni** [comment]
It worked after I changed my task to below (marked in bold)

- name: "Healthcheck | Wait for substitution application to be healthy"
  uri:
    url: "{{ item }}"
    method: GET
    status_code: 200
    validate_certs: no
  register: result
  **until: ('status' in result) and (result.status == 200)
  changed_when: false**
  retries: 4
  delay: 10
  with_items: "https://localhost:8443/health"
  when: substitution_healthcheck_url is defined

**Comment by orachide** [comment]
Great !

But please let me know what is your ansible version `ansible --version` ?

I need to check if that was the real issue.

**Comment by japneet-sahni** [comment]
It's ansible 2.4.2.0

**Comment by orachide** [comment]
I close the isssue as it works for you. Could not reproduce on my side with the same version of ansible.
Also noticed that your are not using the role (you have customize some part of it)
