### ISSUE TITLE
TASK [ Install | Copy application artifact file]

### ISSUE THREAD

**Issue by yobooooi** [orachide/ansible-role-springboot#10]
TASK [orachide.springboot-service : Install | Copy application artifact file] 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option

fatal: [target_server]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/deploy-from/app-1.0.0.war' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

Thank you for this module. I'm just having some issues, is there a way to flag this variable **sb_app_artifact_file** to look on the target server instead of on the Ansible Controller ?

I've attached my main.yaml
[main.txt](https://github.com/orachide/ansible-role-springboot/files/3314281/main.txt)

**Comment by orachide** [comment]
Hello,

Actually, i have already implemented 3 ways to download/copy the artifact:

1. From local (ansible host machine) to the target server
2. From remote maven repo (download occur from the target host
3. From remote maven repo (download occur  on ansible host and then copied to target host)

Could you please explain the use case you are talking about? Where did the artifact come from before being copied on the target server

**Comment by yobooooi** [comment]
Hey,

I eventually got it working. Thanks for the willingness to help. Awesome module BTW
