### ISSUE TITLE
be able to move microservices

### ISSUE THREAD

**Issue by simbo1905** [orachide/ansible-role-springboot#6]
Currently, whether to install or install is based upon `sb_app_state == 'present'` or `sb_app_state == 'absent'`. By default that is set in `defaults\main.yml` as `'present'`. We deploy many microservices to many VMs but not all VMs run all microservices and we would like to be able to move microservices between VMs to rebalance load. So we want an easy way to set `sb_app_state both` per host and per microservice. 

We have come up with [this check](https://github.com/simbo1905/microservices-demo-ansible/blob/cfca2542694633356bab9abb8f01bf818fcc8e99/roles/ansible-role-springboot/tasks/main.yml#L9) that is checking whether the current hostname is in a [per microservice list](https://github.com/simbo1905/microservices-demo-ansible/blob/05d1aac8a7319026e75de00072c578c6e2d9edb1/playbook-install.yml#L33).

**Comment by simbo1905** [comment]
update: someone answered my stackoverflow on how to improve the code so i just edited my original comment above to link to the updated code.

**Comment by simbo1905** [comment]
Here is some background to this feature https://devops.stackexchange.com/q/6393/10599

**Comment by simbo1905** [comment]
I have sent a PR for this.

**Comment by orachide** [comment]
See #7
